In [1]:
!ls

sample_data


In [1]:
!wget https://github.com/sanjquant/TestLab/raw/main/pickle_files/classifier.pickle

--2022-06-03 23:16:55--  https://github.com/sanjquant/TestLab/raw/main/pickle_files/classifier.pickle
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sanjquant/TestLab/main/pickle_files/classifier.pickle [following]
--2022-06-03 23:16:55--  https://raw.githubusercontent.com/sanjquant/TestLab/main/pickle_files/classifier.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2102 (2.1K) [application/octet-stream]
Saving to: ‘classifier.pickle’

classifier.pickle   100%[===================>]   2.05K  --.-KB/s    in 0s      

2022-06-03 23:16:55 (38.0 MB/s) - ‘classifier.pickle’ saved [2102/2102]



# New section

In [3]:
!ls

classifier.pickle  sample_data


In [2]:
!wget https://github.com/sanjquant/TestLab/raw/main/pickle_files/sc.pickle

--2022-06-03 23:17:10--  https://github.com/sanjquant/TestLab/raw/main/pickle_files/sc.pickle
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sanjquant/TestLab/main/pickle_files/sc.pickle [following]
--2022-06-03 23:17:10--  https://raw.githubusercontent.com/sanjquant/TestLab/main/pickle_files/sc.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 497 [application/octet-stream]
Saving to: ‘sc.pickle’

sc.pickle           100%[===================>]     497  --.-KB/s    in 0s      

2022-06-03 23:17:10 (27.0 MB/s) - ‘sc.pickle’ saved [497/497]



In [5]:
!ls

classifier.pickle  sample_data	sc.pickle


In [3]:

import pickle
import numpy as np

In [4]:

local_classifier_colab = pickle.load(open('classifier.pickle', 'rb'))
local_scaler_colab = pickle.load(open('sc.pickle', 'rb'))


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.1.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator StandardScaler from version 1.1.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,


In [5]:
new_predict = local_classifier_colab.predict(local_scaler_colab.transform(np.array([[40, 20000]])))

In [6]:
new_predict

array([0])

In [25]:
new_predict_proba = local_classifier_colab.predict_proba(local_scaler_colab.transform(np.array([[40, 20000]])))[:,1]

In [26]:
new_predict_proba

array([0.4])

In [27]:
new_predict_2 = local_classifier_colab.predict(local_scaler_colab.transform(np.array([[50, 40000]])))
new_predict_proba_2 = local_classifier_colab.predict_proba(local_scaler_colab.transform(np.array([[50, 40000]])))[:,1]

In [28]:
new_predict_2

array([1])

In [29]:
new_predict_proba_2

array([1.])