In [1]:
"""
Build a Classification model to predict store pirchase of a person based on Age and Salary:
"""

'\nBuild a Classification model to predict store pirchase of a person based on Age and Salary:\n'

In [2]:
import numpy as np 
import pandas as pd

In [3]:
training_data = pd.read_csv("../Data/storepurchasedata.csv")

In [32]:
training_data.describe()

Age        Salary  Purchased
count  40.000000     40.000000  40.000000
mean   38.100000  49525.000000   0.550000
std    12.557151  19046.484971   0.503831
min    18.000000  20000.000000   0.000000
25%    27.750000  35000.000000   0.000000
50%    37.500000  48500.000000   1.000000
75%    47.250000  60000.000000   1.000000
max    60.000000  95000.000000   1.000000

In [4]:
training_data.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   50000          1

In [5]:
X =training_data.iloc[:,:-1].values
Y =training_data.iloc[:,-1].values

In [6]:
X.shape , Y.shape

((40, 2), (40,))

In [7]:
type(X) , type(Y)

(numpy.ndarray, numpy.ndarray)

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size =.20,random_state=0)

In [10]:
len(X_test)/len(X_train)

0.25

In [11]:
sc = StandardScaler()  ## Standardizing the data

In [33]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [13]:
""" 
Build a Classifcation model : 
## We are using KNN Classifier in this example : 
*n_neighbour =5 -* Number of neighbours
*metric = 'minkowski', p=2* - For Eucledian distance calculation

"""

" \nBuild a Classifcation model : \n## We are using KNN Classifier in this example : \n*n_neighbour =5 -* Number of neighbours\n*metric = 'minkowski', p=2* - For Eucledian distance calculation\n\n"

In [34]:
from sklearn.neighbors import KNeighborsClassifier
# minkowski is for ecledian distance
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

In [35]:
# Model training
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_prob = classifier.predict_proba(X_test)[:,1]

In [49]:
y_pred , y_prob

(array([1, 1, 1, 0, 1, 0, 0, 0], dtype=int64),
 array([1. , 0.8, 1. , 0.2, 0.8, 0. , 0.4, 0.2]))

In [50]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

In [51]:
cm

array([[3, 0],
       [1, 4]], dtype=int64)

In [53]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.875


In [54]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         3
           1       1.00      0.80      0.89         5

    accuracy                           0.88         8
   macro avg       0.88      0.90      0.87         8
weighted avg       0.91      0.88      0.88         8



In [55]:
new_prediction = classifier.predict(sc.transform(np.array([[40,20000]])))

In [56]:
new_prediction

array([0], dtype=int64)

In [57]:
new_prediction_proba = classifier.predict_proba(sc.transform(np.array([[40,20000]])))[:,1]

In [58]:
new_prediction_proba

array([0.4])

In [63]:
new_pred = classifier.predict(sc.transform(np.array([[42,50000]])))[0]

In [64]:
new_pred

1

In [65]:
new_pred_proba = classifier.predict_proba(sc.transform(np.array([[42,50000]])))[:,1]

In [66]:
new_pred_proba

array([1.])

In [29]:
import pickle

In [30]:

model_file = "../pickle_files/classifier.pickle"
pickle.dump(classifier, open(model_file,'wb'))


In [31]:
scaler_file = "../pickle_files/sc.pickle"

pickle.dump(sc, open(scaler_file,'wb'))