In [ ]:
"""
Build a Classification model to predict store pirchase of a person based on Age and Salary:
"""

In [31]:
import numpy as np 
import pandas as pd

In [32]:
training_data = pd.read_csv("../Data/storepurchasedata.csv")

In [33]:
training_data.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   50000          1

In [34]:
X =training_data.iloc[:,:-1].values
Y =training_data.iloc[:,-1].values

In [35]:
X.shape , Y.shape

((40, 2), (40,))

In [36]:
type(X) , type(Y)

(numpy.ndarray, numpy.ndarray)

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, stratify=Y, random_state=0)

In [39]:
len(X_test)/len(X_train)

0.3333333333333333

In [40]:
sc = StandardScaler()  ## Standardizing the data

In [41]:
X_train = sc.fit_transform(X_train)
X_train = sc.fit_transform(X_train)

In [42]:
""" 
Build a Classifcation model : 
## We are using KNN Classifier in this example : 
*n_neighbour =5 -* Number of neighbours
*metric = 'minkowski', p=2* - For Eucledian distance calculation

"""

" \nBuild a Classifcation model : \n## We are using KNN Classifier in this example : \n*n_neighbour =5 -* Number of neighbours\n*metric = 'minkowski', p=2* - For Eucledian distance calculation\n\n"

In [43]:
from sklearn.neighbors import KNeighborsClassifier
# minkowski is for ecledian distance
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

In [44]:
# Model training
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_prob = classifier.predict_proba(X_test)[:,1]

In [45]:
y_pred , y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 0, 0, 1, 0, 1, 1, 1, 0], dtype=int64))

In [46]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

In [47]:
cm

array([[0, 5],
       [0, 5]], dtype=int64)

In [48]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.5


In [49]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.50      1.00      0.67         5

    accuracy                           0.50        10
   macro avg       0.25      0.50      0.33        10
weighted avg       0.25      0.50      0.33        10



c:\ProgramData\Anaconda_3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\Anaconda_3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\Anaconda_3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
new_prediction = classifier.predict(sc.transform(np.array([[40,20000]])))

In [51]:
new_prediction

array([1], dtype=int64)

In [52]:
new_prediction_proba = classifier.predict_proba(sc.transform(np.array([[40,20000]])))[:,1]

In [53]:
new_prediction_proba

array([1.])

In [54]:
new_pred = classifier.predict(sc.transform(np.array([[42,50000]])))

In [55]:
new_pred

array([1], dtype=int64)

In [57]:
new_pred_proba = classifier.predict_proba(sc.transform(np.array([[42,50000]])))[:,1]

In [58]:
new_pred_proba

array([1.])

In [59]:
import pickle

In [62]:

model_file = "../pickle_files/classifier.pickle"
pickle.dump(classifier, open(model_file,'wb'))


In [63]:
scaler_file = "../pickle_files/sc.pickle"

pickle.dump(sc, open(scaler_file,'wb'))