In [10]:
"""
Deploy the pickle file and Testing the model locally : 

"""

'\nDeploy the pickle file and Testing the model locally : \n\n'

In [11]:

import pickle
import numpy as np


In [12]:


local_classifier = pickle.load(open('../pickle_files/classifier.pickle', 'rb'))
local_scaler = pickle.load(open('../pickle_files/sc.pickle', 'rb'))



In [13]:
new_predict = local_classifier.predict(local_scaler.transform(np.array([[40, 20000]])))

In [14]:
new_predict

array([1], dtype=int64)

In [15]:
new_predict_proba = local_classifier.predict_proba(local_scaler.transform(np.array([[40, 20000]])))

In [16]:
new_predict_proba

array([[0., 1.]])

In [17]:
new_predict_proba[:,1]

array([1.])

In [18]:
new_predict_2 = local_classifier.predict(local_scaler.transform(np.array([[42, 20000]])))
new_predict_proba_2 = local_classifier.predict_proba(local_scaler.transform(np.array([[40, 20000]])))[:,-1]

In [22]:
new_predict_2, new_predict_proba_2


(array([1], dtype=int64), array([1.]))